name: ci-cd test

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev

jobs:

  test:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      

      - name: Run tests
        env:
          SQLALCHEMY_DATABASE_URL: ${{ secrets.SQLALCHEMY_TEST_DATABASE_URL }}
        run: |
          pytest


  docker-build-and-push:

    runs-on: ubuntu-latest
    needs: test
    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag santiagoescobar/facturas
    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD}}" | docker login -u "${{secrets.DOCKER_USERNAME}}" --password-stdin
    - name: Push the Docker image
      run: docker push santiagoescobar/facturas

  publish-to-render:
    
    runs-on: ubuntu-latest
    needs: docker-build-and-push
    steps:
    - name: Deploy to Render
      uses: gh-actions-workflows/deploy-docker-render@v1.1
      with:
        deploy-hook: ${{ secrets.RENDER_DEPLOY_HOOK }}
        image-url: ${{secrets.DOCKER_USERNAME}}/facturas:latest      