name: ci-cd test

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev

jobs:

  test:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: |
          pytest
  docker-build:

    runs-on: ubuntu-latest
    needs: test
    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag facturas:$(date +%s)

  build:
    runs-on: ubuntu-latest
    needs: docker-build
    steps:
      - name: Deploy to production
        uses: johnbeynon/render-deploy-action@v0.0.8
        with:
          service-id: rv-cpfs196ct0pc73d2cbl0
          api-key: rnd_ujUqvpR3RghjcJ0uHdi59LxxaKQN