name: ci-cd test

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev

jobs:

  test:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: |
          pytest


  docker-push:

    runs-on: ubuntu-latest
    needs: test
    steps:
    - name: Deploy to Render
      uses: gh-actions-workflows/deploy-docker-render@v1.1
      with:
        deploy-hook: https://api.render.com/deploy/srv-cph4d90cmk4c73bs5oq0?key=x7-KIQ8Stek
        image-url: santiagoescobar/facturas:latest